// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MusteriUrunDegisti : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MusteriUrunDegisti));
        
        string IMigrationMetadata.Id
        {
            get { return "202204011719155_MusteriUrunDegisti"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
